name: Docker Image CI

on:
  push:
    branches: [ "fet" ]
  pull_request:
    branches: [ "fet" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f back-end/agropec/Dockerfile back-end/agropec --tag agropec_api_img:$(date +%s)
